### ISSUE TITLE
Exception thrown when running on an iPad that does not have FlashLight

### ISSUE THREAD

**Issue by DeRuDev** [ChainTechNetwork/QRKitComposeMultiplatform#1]
When the scan Button is clicked on an iPad that does not have flashlight, the below exception is thrown:

Exception	NSException *	"*** -[AVCaptureDevice setTorchMode:] 
The passed torchMode 0 is not supported - use -isTorchModeSupported: to discover valid torch modes"

above issue replicated on iPad Mini 5
above issue not appearing on iPhone 12

**Comment by ctn-mobile-innovation** [comment]
Noted! we will fix this in next release. Thanks For reporting.

**Comment by ctn-mobile-innovation** [comment]
It has been fixed in Latest version
